<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class CheckLateAbsencesCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'attendance:check-late-absences';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Secara agresif mengecek jadwal yang baru saja berakhir dan memberikan penalti alpa bagi yang tidak hadir';

    protected \App\Services\PenaltyService $penaltyService;
    protected \App\Services\AttendanceService $attendanceService;

    public function __construct(\App\Services\PenaltyService $penaltyService, \App\Services\AttendanceService $attendanceService)
    {
        parent::__construct();
        $this->penaltyService = $penaltyService;
        $this->attendanceService = $attendanceService;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $now = now();
        $today = today();
        $currentTime = $now->format('H:i:s');

        $this->info("Memeriksa absensi yang terlewat pada waktu: {$currentTime}");

        // Cari jadwal HARI INI yang berstatus scheduled (belum diabsen)
        // dan jam pulangnya (time_end) sudah lewat dari jam sekarang
        $missedAssignments = \App\Models\ScheduleAssignment::where('date', $today)
            ->where('status', 'scheduled')
            ->where('time_end', '<', $currentTime)
            ->get();

        if ($missedAssignments->isEmpty()) {
            $this->info("Tidak ada jadwal yang terlewat saat ini.");
            return \Illuminate\Console\Command::SUCCESS;
        }

        $this->info("Ditemukan {$missedAssignments->count()} jadwal yang terlewat.");
        $count = 0;

        foreach ($missedAssignments as $assignment) {
            // Validasi ulang: Pastikan benar-benar tidak ada absensi
            $hasAttendance = \App\Models\Attendance::where('user_id', $assignment->user_id)
                ->where('schedule_assignment_id', $assignment->id)
                ->exists();

            if ($hasAttendance) {
                continue;
            }

            // Validasi izin cuti
            $hasApprovedLeave = $this->attendanceService->hasApprovedLeave($assignment->user_id, $today);
            if ($hasApprovedLeave) {
                continue;
            }

            // Eksekusi Penalti
            \Illuminate\Support\Facades\DB::transaction(function () use ($assignment, $today) {
                // 1. Buat record absensi berstatus Alpa
                $attendance = \App\Models\Attendance::create([
                    'user_id' => $assignment->user_id,
                    'schedule_assignment_id' => $assignment->id,
                    'date' => $today,
                    'status' => 'absent',
                    'notes' => 'Tidak hadir (Auto-generated by System)',
                ]);

                // 2. Berikan Penalti Alpa (25 Poin)
                $this->penaltyService->createPenalty(
                    $assignment->user_id,
                    'ABSENT',
                    "Tidak hadir pada {$today->locale('id')->isoFormat('dddd, D MMMM Y')} - Sesi {$assignment->session}",
                    'attendance',
                    $attendance->id,
                    $today
                );

                // 3. Ubah status penugasan menjadi missed
                $assignment->update(['status' => 'missed']);

                \Illuminate\Support\Facades\Log::info("Penalti Alpa Instan diberikan", [
                    'user_id' => $assignment->user_id,
                    'assignment_id' => $assignment->id
                ]);
            });

            $this->info("✓ Memberikan penalti alpa ke User ID: {$assignment->user_id} (Sesi {$assignment->session})");
            $count++;
        }

        $this->info("Selesai memproses {$count} penalti alpa instan.");
        return \Illuminate\Console\Command::SUCCESS;
    }
}
