<?php

namespace App\Console\Commands;

use App\Models\Attendance;
use App\Models\ScheduleAssignment;
use App\Services\AttendanceService;
use App\Services\PenaltyService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class CheckLateAbsencesCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'attendance:check-late-absences';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Secara agresif mengecek jadwal yang baru saja berakhir dan memberikan penalti alpa bagi yang tidak hadir';

    protected PenaltyService $penaltyService;
    protected AttendanceService $attendanceService;

    public function __construct(PenaltyService $penaltyService, AttendanceService $attendanceService)
    {
        parent::__construct();
        $this->penaltyService = $penaltyService;
        $this->attendanceService = $attendanceService;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $now = now();
        $today = today();
        $currentTime = $now->format('H:i:s');

        $this->info("Memeriksa absensi yang terlewat pada waktu: {$currentTime}");

        // Cari jadwal HARI INI yang:
        // 1. Berstatus 'scheduled' (belum ada check-in yang mengubah ke 'in_progress')
        // 2. Jam pulangnya (time_end) sudah lewat dari jam sekarang
        // 3. Jadwal induk (schedule) berstatus 'published'
        $missedAssignments = ScheduleAssignment::where('date', $today)
            ->where('status', 'scheduled')
            ->where('time_end', '<', $currentTime)
            ->whereHas('schedule', fn($q) => $q->where('status', 'published'))
            ->get();

        if ($missedAssignments->isEmpty()) {
            $this->info("Tidak ada jadwal yang terlewat saat ini.");
            return Command::SUCCESS;
        }

        $this->info("Ditemukan {$missedAssignments->count()} jadwal yang terlewat.");
        $processedCount = 0;
        $skippedCount = 0;

        foreach ($missedAssignments as $assignment) {
            // Validasi ulang: Pastikan benar-benar tidak ada absensi
            $hasAttendance = Attendance::where('user_id', $assignment->user_id)
                ->where('schedule_assignment_id', $assignment->id)
                ->exists();

            if ($hasAttendance) {
                $this->line("  Skipping assignment #{$assignment->id} (user #{$assignment->user_id}) - sudah ada attendance");
                $skippedCount++;
                continue;
            }

            // Validasi izin cuti
            $hasApprovedLeave = $this->attendanceService->hasApprovedLeave($assignment->user_id, $today);
            if ($hasApprovedLeave) {
                $this->line("  Skipping assignment #{$assignment->id} (user #{$assignment->user_id}) - punya izin cuti");
                $skippedCount++;
                continue;
            }

            // Eksekusi Penalti
            try {
                DB::transaction(function () use ($assignment, $today) {
                    // 1. Buat record absensi berstatus absent
                    $attendance = Attendance::create([
                        'user_id' => $assignment->user_id,
                        'schedule_assignment_id' => $assignment->id,
                        'date' => $today,
                        'status' => 'absent',
                        'notes' => 'Tidak hadir (Auto-generated by System)',
                    ]);

                    // 2. Berikan Penalti ABSENT
                    $this->penaltyService->createPenalty(
                        $assignment->user_id,
                        'ABSENT',
                        "Tidak hadir pada {$today->locale('id')->isoFormat('dddd, D MMMM Y')} - Sesi {$assignment->session}",
                        'attendance',
                        $attendance->id,
                        $today
                    );

                    // 3. Ubah status penugasan menjadi missed
                    $assignment->update(['status' => 'missed']);

                    Log::info('Penalti Alpa Instan diberikan', [
                        'user_id' => $assignment->user_id,
                        'assignment_id' => $assignment->id,
                        'attendance_id' => $attendance->id,
                    ]);
                });

                $this->info("  ✓ Memberikan penalti alpa ke User ID: {$assignment->user_id} (Sesi {$assignment->session})");
                $processedCount++;
            } catch (\Exception $e) {
                $this->error("  ✗ Gagal memproses assignment #{$assignment->id}: {$e->getMessage()}");
                Log::error('Gagal memberikan penalti alpa instan', [
                    'assignment_id' => $assignment->id,
                    'user_id' => $assignment->user_id,
                    'error' => $e->getMessage(),
                ]);
            }
        }

        $this->newLine();
        $this->info("Selesai: {$processedCount} diproses, {$skippedCount} dilewati, {$missedAssignments->count()} total diperiksa.");
        return Command::SUCCESS;
    }
}
